### ISSUE TITLE
Adding a response header results in an error

### ISSUE THREAD

**Issue by WST** [unbit/uwsgi-phpsgi#1]
I start with a simple test application based on your example.

``` php
function application($env) {
    ob_start();
    print_r($env);
    $foo = ob_get_contents();
    ob_clean();
    return ["200 OK", ["Content-Type" => "text/plain"], [ $foo ]];
}
```

And a simple uWSGI vassal configuration.

``` ini
[uwsgi]
plugins = phpsgi,geoip
socket = 127.0.0.1:23032
http-socket = :9090
master = true
chdir = /path/to/phpsgi.averkov.net
uid = user
max-requests = 10
```

However, I can run it only using http-socket, all of my attempts to run it using uwsgi socket have failed. Nginx error log says:

```
2015/02/06 09:08:22 [error] 3067#0: *230 upstream sent invalid header while reading response header from upstream, client: 83.239.227.202, server: phpsgi.averkov.net, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:23032", host: "phpsgi.averkov.net"
```

Interestingly, passing an empty array of headers results in the application starting to work as expected. I tried adding a proper Content-Length, but it did not change anything.

**Comment by unbit** [comment]
Should be fixed now
