### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by MechanisM** [unbit/uwsgi-phpsgi#5]
👦 server 💻 MechanisM 📂  ~/uwsgi [git:master] 😒  /server/bin/uwsgi --build-plugin https://github.com/unbit/uwsgi-phpsgi
**\* uWSGI building and linking plugin from https://github.com/unbit/uwsgi-phpsgi ***
Already up-to-date.
[x86_64-linux-gnu-gcc -pthread] phpsgi_plugin.so
/usr/bin/ld: cannot find -ldb
/usr/bin/ld: cannot find -lbz2
/usr/bin/ld: cannot find -lgssapi_krb5
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lk5crypto
collect2: error: ld returned 1 exit status
**\* unable to build phpsgi plugin ***

Please let me know which dependencies are missing? I have php5-dev and libphp5-embed-dev installed

**Comment by bazilio91** [comment]
`apt-get install libphp5-embed libkrb5-dev libxml2-dev libbz2-dev libonig-dev libdb-dev libqdbm-dev`

**Comment by MechanisM** [comment]
Thanks @bazilio91! It's worked!

**Comment by MechanisM** [comment]
But these dependencies should be listed in readme!
